"""Add file_hash to Document model

Revision ID: 5b7c882af3a0
Revises: 19b9d1c244b3
Create Date: 2025-10-21 13:05:03.157220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b7c882af3a0'
down_revision: Union[str, Sequence[str], None] = '19b9d1c244b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_hash', sa.String(), nullable=False))
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_column('documents', 'file_hash')
    # ### end Alembic commands ###
