"""Remove user_id from Document model

Revision ID: 5f23ca0be181
Revises: 6be3f60b1f10
Create Date: 2025-10-21 22:12:14.091366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f23ca0be181'
down_revision: Union[str, Sequence[str], None] = '6be3f60b1f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(op.f('ix_documents_user_id'))
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_index(op.f('ix_documents_user_id'), ['user_id'], unique=False)
    # ### end Alembic commands ###
